version: '3.3'
services:
  postgres:
    container_name: vapeSkidel
    image: postgres
    environment:
      - POSTGRES_DB=VapeShopSenla
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
  web:
    depends_on:
      - postgres
    image: tomcat
    ports:
      - "8081:8080"
    volumes:
      - ./target/SenlaIntencive8-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/senla.war